name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    uses: ./.github/workflows/2task.yml # the reusable workflow
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

