# name: Main Workflow

# on:
#   push:
#     branches:
#       - main

# jobs:
#   terraform-deploy:
#     uses: ./.github/workflows/2task.yml # Reusable Terraform Workflow
#     secrets:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_REGION: ${{ secrets.AWS_REGION }}
#       AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#H
name: Main Workflow
on:
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        run: terraform init 
        working-directory: ./2task 

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./2task 

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./2task 



 



