name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./1task/.github/workflows/terraform.yml@main # the reusable workflow
    with:
      apply: true
      destroy: false
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
