name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/terraform.yml # the reusable workflow
    # with:
    #   apply: true
    #   destroy: false
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
