name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Should we destroy the Terraform resources?'
        required: false
        default: false 
        type: boolean     
  push:
    branches:
      - main

jobs:
  terraform-deploy:
    uses: ./.github/workflows/terraform.yml # the reusable workflow
    with: 
      destroy: ${{ github.event.inputs.destroy == 'true' }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

