#.\1task\.github\workflows\terraform.yml
name: Reusable Terraform Workflow
on:
  # workflow_dispatch:  # -> manual execution from the Actions tab
  workflow_call:  # this workflow can be reused
    inputs:
      apply:
        required: true
        type: boolean
      destroy:
        required: false
        type: boolean
    secrets:  # passes secrets to the reusable workflow
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: pwd 
        run: pwd
      - name: ls-la 
        run: ls -la

      - name: ls -la 1task
        run: ls -la 1task

      - name: cd 
        run: cd 1task

      - name: Terraform Init and Apply (Create Bucket)
        run: |
          cd 1task
          terraform init
          terraform apply -auto-approve

      - name: Configure Backend and Plan
        run: |
          cd 1task/iam
          terraform init -reconfigure  # Re-initialize with the backend configuration
          terraform plan

      - name: Terraform Apply
        if: ${{ inputs.apply == 'true' }}
        run: |
          cd 1task/iam
          terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ inputs.destroy == 'true' }}
        run: |
          cd 1task
          terraform destroy -auto-approve
          cd 1task/iam
          terraform destroy -auto-approve


