name: Reusable Terraform Workflow
on:
  workflow_dispatch:  # Manual execution from the Actions tab
  workflow_call:  
    inputs:
      init:
        description: 'Should we initialize Terraform?'
        required: false
        default: 'false'
      check:
        description: 'Should we format the Terraform files?'
        required: false
        default: 'false' 
      plan:
        description: 'Should we create a Terraform plan?'
        required: false
        default: 'false'
      apply:
        description: 'Should we apply the Terraform changes?'
        required: false
        default: 'false'
      destroy:
        description: 'Should we destroy the Terraform resources?'
        required: false
        default: 'false' 
    secrets:  
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.init == 'true' }}  # Only run if 'init' is true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd 1task
          terraform init -reconfigure

  terraform-check:
    runs-on: ubuntu-latest
    needs: terraform-init
    if: ${{ github.event.inputs.check == 'true' }}  # Run if 'check' is true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Check
        run: |
          cd 1task
          terraform fmt

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-init
    if: ${{ github.event.inputs.plan == 'true' }}  # Run if 'plan' is true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Plan
        run: |
          cd 1task
          terraform plan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: ${{ github.event.inputs.apply == 'true' }}  # Run if 'apply' is true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Apply
        run: |
          cd 1task
          terraform apply -auto-approve

  terraform-destroy:
    runs-on: ubuntu-latest
    needs: terraform-apply
    if: ${{ github.event.inputs.destroy == 'true' }}  # Run if 'destroy' is true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform Destroy
        run: |
          cd 1task
          terraform destroy -auto-approve




