name: Reusable Terraform Workflow

on:
  workflow_call: 
    inputs: 
      destroy:
        description: 'Should we destroy the Terraform resources?'
        required: false
        default: false  
        type: boolean  
    secrets:  
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    # needs: setup  # Depend on the setup job
    steps:
      - name: Terraform Init
        run: |
          cd 1task
          terraform init -reconfigure

  terraform-check:
    runs-on: ubuntu-latest
    needs: terraform-init  # Ensure init runs first
    steps:
      - name: Terraform Check
        run: |
          cd 1task
          terraform fmt 

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check  # Ensure check runs first
    steps:
      - name: Terraform Plan
        run: |
          cd 1task
          terraform plan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan  # Ensure plan runs first
    steps:
      - name: Terraform Apply
        run: |
          cd 1task
          terraform apply -auto-approve

  terraform-destroy:
    runs-on: ubuntu-latest
    needs: terraform-apply  # Ensure apply runs first
    if: ${{ inputs.destroy == 'true' }}  # Run if 'destroy' input is true
    steps:
      - name: Terraform Destroy
        run: |
          cd 1task
          terraform destroy -auto-approve






